---

- name: Install Basic Packages
  hosts: all
  remote_user: ansible
  become: yes

  tasks:
    - name: Ensure necessary packages are installed 
      yum:
        name: 
          - numactl
          - unzip 
        state: latest
      
    - name: Creating file to kick off the startup scripts
      file:
        path: "/tmp/ansible_ready"
        state: touch