name: Terraform Deployment

on:
  push:
    branches:
      - main
      - 'feature/**'

jobs:
  terraform_deployment:
      name: "Terraform Deployment"
      runs-on: macos-latest
      defaults:
        run:
          shell: bash

      steps: 
      - name: checkout codebase
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.2.8

      - name: 'Set up Cloud SDK'
        id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
        with:
          project_id: 'devops-361723'
    
      - name: Adding ansible private key to be used for verifying instance creation
        id: ansible_private
        run: |
        cat << EOF > ~/.ssh/ansible_ed25519
        ${{ secrets.ANSIBLE_PRIV }}
        EOF
        chmod 600 ~/.ssh/ansible_ed25519

      - name: Terraform fmt code from base dir 
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform initialize from base dir 
        id: init
        run: terraform init

      - name: Terraform plan 
        id: plan
        run: terraform plan -var-file=terraform.tfvars -out=tfplan

      - name: Terraform apply 
        id: apply
        run: terraform apply -auto-approve -input=false tfplan
        continue-on-error: true

      - name: Terraform destroy 
        id: destroy
        run: terraform destroy -auto-approve -input=false
  
